### ISSUE TITLE
Incorrect screenshot

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/generic-scratch3-paint-new-backdrop#5]
The second screenshot needs to be replaced as the ui has changed slightly since the ingredient was created. This used to say 'Costumes' and that's what we have in the ingredient, but as you can see it has now been replaced with 'Backdrops':

![image](https://user-images.githubusercontent.com/33628387/51107536-f9a88a80-17e6-11e9-926c-a681a59dba4f.png)

**Comment by martinohanlon** [comment]
Fixed with #6
